---
# ansible/roles/common/handlers/main.yml

- name: restart ssh
  systemd:
    name: ssh
    state: restarted

- name: restart cron
  systemd:
    name: cron
    state: restarted

- name: restart docker
  systemd:
    name: docker
    state: restarted

- name: reboot if required
  reboot:
    msg: "Reboot initiated by Ansible for system updates"
    connect_timeout: 5
    reboot_timeout: 600
    pre_reboot_delay: 0
    post_reboot_delay: 30
    test_command: whoami
  when: ansible_facts['os_family'] == "Debian"