---
# ansible/main.yml
- name: Configure Ubuntu 22.04 Vagrant Box
  hosts: localhost
  connection: local
  become: yes
  gather_facts: yes

  vars:
    vagrant_user: vagrant
    nodejs_version: "18.x"

  pre_tasks:
    - name: Update apt cache
      apt:
        update_cache: yes
        cache_valid_time: 86400

  roles:
    - common

  tasks:
    - name: Install additional development packages
      apt:
        name:
          - jq
          - tmux
          - screen
          - nano
          - less
          - rsync
          - zip
          - unrar
          - p7zip-full
          - mc
          - ncdu
          - iotop
          - nethogs
          - nmap
          - tcpdump
          - strace
          - lsof
        state: present

    - name: Configure Git global settings for vagrant user
      become_user: "{{ vagrant_user }}"
      git_config:
        name: "{{ item.name }}"
        value: "{{ item.value }}"
        scope: global
      loop:
        - { name: "user.name", value: "Vagrant User" }
        - { name: "user.email", value: "vagrant@localhost" }
        - { name: "init.defaultBranch", value: "main" }
        - { name: "pull.rebase", value: "false" }

    - name: Create useful directories for vagrant user
      file:
        path: "/home/{{ vagrant_user }}/{{ item }}"
        state: directory
        owner: "{{ vagrant_user }}"
        group: "{{ vagrant_user }}"
        mode: '0755'
      loop:
        - projects
        - scripts
        - tmp

    - name: Install Python packages via pip
      pip:
        name:
          - requests
          - PyYAML
          - jinja2
          - setuptools
          - wheel
        executable: pip3
        state: latest

    - name: Configure bashrc with additional aliases
      blockinfile:
        path: "/home/{{ vagrant_user }}/.bashrc"
        block: |
          # Custom aliases and functions
          alias dps='docker ps --format "table {{.Names}}\t{{.Status}}\t{{.Ports}}"'
          alias dlog='docker logs -f'
          alias dexec='docker exec -it'
          alias dc='docker-compose'
          alias dcup='docker-compose up -d'
          alias dcdown='docker-compose down'
          alias dcps='docker-compose ps'
          alias dclogs='docker-compose logs -f'
          
          # Git aliases
          alias gs='git status'
          alias ga='git add'
          alias gc='git commit'
          alias gp='git push'
          alias gl='git log --oneline -10'
          alias gb='git branch'
          alias gco='git checkout'
          
          # System aliases
          alias df='df -h'
          alias du='du -h'
          alias free='free -h'
          alias ports='netstat -tuln'
          alias myip='curl -s ipinfo.io/ip'
        marker: "# {mark} ANSIBLE MANAGED BLOCK - Custom aliases"
        owner: "{{ vagrant_user }}"
        group: "{{ vagrant_user }}"

    - name: Configure vim with enhanced settings
      copy:
        dest: "/home/{{ vagrant_user }}/.vimrc"
        content: |
          " Enhanced Vim configuration
          set number
          set relativenumber
          set expandtab
          set tabstop=2
          set shiftwidth=2
          set softtabstop=2
          set autoindent
          set smartindent
          set wrap
          set linebreak
          set showmatch
          set hlsearch
          set incsearch
          set ignorecase
          set smartcase
          syntax on
          set background=dark
          
          " Enable mouse support
          set mouse=a
          
          " Show current mode
          set showmode
          
          " Enable file type detection
          filetype on
          filetype plugin on
          filetype indent on
          
          " Status line
          set laststatus=2
          set statusline=%F%m%r%h%w\ [FORMAT=%{&ff}]\ [TYPE=%Y]\ [POS=%l,%v][%p%%]\ %{strftime(\"%d/%m/%y\ -\ %H:%M\")}
        owner: "{{ vagrant_user }}"
        group: "{{ vagrant_user }}"
        mode: '0644'

    - name: Install Oh My Bash for enhanced terminal experience
      git:
        repo: https://github.com/ohmybash/oh-my-bash.git
        dest: "/home/{{ vagrant_user }}/.oh-my-bash"
        force: yes
      become_user: "{{ vagrant_user }}"

    - name: Configure Oh My Bash
      template:
        src: bashrc.j2
        dest: "/home/{{ vagrant_user }}/.bashrc_omg"
        owner: "{{ vagrant_user }}"
        group: "{{ vagrant_user }}"
        mode: '0644'

  handlers:
    - name: restart ssh
      service:
        name: ssh
        state: restarted

    - name: restart docker
      service:
        name: docker
        state: restarted